# Generated by Django 4.1.3 on 2022-11-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=False, max_digits=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('address', models.TextField(max_length=1000)),
                ('is_published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000)),
            ],
        ),
    ]
